name: CI/CD â€“ Build, Push & Rollout (Docker Hub + SSH)

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  REGISTRY: docker.io
  NAMESPACE: app-demo

  FRONT_DEPLOYMENT: frontend
  FRONT_CONTAINER: app
  BACK_DEPLOYMENT: backend
  BACK_CONTAINER: app

  FRONT_IMAGE: lufllp/frontend:avaliacao
  BACK_IMAGE: lufllp/backend:avaliacao

jobs:
  build-and-push:
    name: Build & Push (frontend + backend)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # ---------- FRONTEND ----------
      - name: Build & Push Frontend
        uses: docker/build-push-action@v6
        with:
          context: ./client
          file: ./client/Dockerfile
          push: true
          tags: ${{ env.FRONT_IMAGE }}
          cache-from: type=gha,scope=frontend
          cache-to: type=gha,mode=max,scope=frontend

      # ---------- BACKEND ----------
      - name: Build & Push Backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ env.BACK_IMAGE }}
          cache-from: type=gha,scope=backend
          cache-to: type=gha,mode=max,scope=backend

  deploy:
    name: Rollout via SSH on EC2
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Add EC2 host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: Rollout with SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.REMOTE_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            set -euo pipefail
            export KUBECONFIG=/etc/rancher/k3s/k3s.yaml

            echo ">> Reiniciando FRONTEND"
            sudo kubectl -n app-demo rollout restart deployment/frontend

            echo ">> Reiniciando BACKEND"
            sudo kubectl -n app-demo rollout restart deployment/backend
  
